spring:
  profiles:
    active: mongo

security:
  jwt:
    secret: ${JWT_SECRET:HOLA_ESTE_ES_EL_SECRET_QUE_FIRMA_JWT_2026_ABCDEF123456}
    ttl-ms: 3600000

server:
  port: ${PORT:8080}
  ssl:
    enabled: false